<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\ApplicationTariff;

ApplicationTariff::truncate();

$tariffs = [
    // 1. FEES IN RESPECT OF ISSUING CERTIFICATES
    [
        'category' => '1. FEES IN RESPECT OF ISSUING CERTIFICATES',
        'item_no' => '1',
        'description_en' => "Application Fee for General Manager's Certificate",
        'scale' => 'All properties',
        'fee' => 500.00,
        'fee_display' => null,
        'remarks' => 'Applicable for Condominium, Semi-Condominium, or Provisional Condominium Plans.',
        'order' => 10,
    ],
    [
        'category' => '1. FEES IN RESPECT OF ISSUING CERTIFICATES',
        'item_no' => '2',
        'description_en' => 'Processing Fee for Preliminary Clearance Letter',
        'scale' => 'Advance payment',
        'fee' => 0.00,
        'fee_display' => '25%',
        'remarks' => '25% of the processing fee to be paid at the time of obtaining the letter.',
        'order' => 20,
    ],

    // 2. APPLICATION TO TERMINATE CONDOMINIUM STATUS OR DEMOLISH PROPERTY
    [
        'category' => '2. APPLICATION TO TERMINATE CONDOMINIUM STATUS OR DEMOLISH PROPERTY',
        'item_no' => null,
        'description_en' => 'Units from 2 - 5',
        'scale' => 'Termination Fee',
        'fee' => 2000.00,
        'fee_display' => null,
        'remarks' => 'Subject to Authority approval and government taxes.',
        'order' => 30,
    ],
    [
        'category' => '2. APPLICATION TO TERMINATE CONDOMINIUM STATUS OR DEMOLISH PROPERTY',
        'item_no' => null,
        'description_en' => 'Units from 6 - 10',
        'scale' => 'Termination Fee',
        'fee' => 5000.00,
        'fee_display' => null,
        'remarks' => 'Subject to Authority approval and government taxes.',
        'order' => 40,
    ],
    [
        'category' => '2. APPLICATION TO TERMINATE CONDOMINIUM STATUS OR DEMOLISH PROPERTY',
        'item_no' => null,
        'description_en' => 'Units from 11 - 25',
        'scale' => 'Termination Fee',
        'fee' => 7500.00,
        'fee_display' => null,
        'remarks' => 'Subject to Authority approval and government taxes.',
        'order' => 50,
    ],
    [
        'category' => '2. APPLICATION TO TERMINATE CONDOMINIUM STATUS OR DEMOLISH PROPERTY',
        'item_no' => null,
        'description_en' => 'More than 26 units',
        'scale' => 'Termination Fee',
        'fee' => 15000.00,
        'fee_display' => null,
        'remarks' => 'Subject to Authority approval and government taxes.',
        'order' => 60,
    ],

    // 3. Processing Fees of Applications Submitted in Respect of a Condominium Property
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: 0 - 500 m²',
        'scale' => 'Residential',
        'fee' => 30.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 70,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: 0 - 500 m²',
        'scale' => 'Commercial',
        'fee' => 50.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 80,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: 501 - 1,000 m²',
        'scale' => 'Residential',
        'fee' => 75.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 90,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: 501 - 1,000 m²',
        'scale' => 'Commercial',
        'fee' => 150.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 100,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: 1,001 - 3,000 m²',
        'scale' => 'Residential',
        'fee' => 250.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 110,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: 1,001 - 3,000 m²',
        'scale' => 'Commercial',
        'fee' => 450.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 120,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: 3,001 - 5,000 m²',
        'scale' => 'Residential',
        'fee' => 300.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 130,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: 3,001 - 5,000 m²',
        'scale' => 'Commercial',
        'fee' => 500.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 140,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: More than 5,001 m²',
        'scale' => 'Residential',
        'fee' => 600.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 150,
    ],
    [
        'category' => '3. Processing Fees of Applications Submitted in Respect of a Condominium Property',
        'item_no' => null,
        'description_en' => 'Floor Area: More than 5,001 m²',
        'scale' => 'Commercial',
        'fee' => 850.00,
        'fee_display' => null,
        'remarks' => 'Fee calculated per 1 m²',
        'order' => 160,
    ],

    // 4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: 500 - 1,000 m²',
        'scale' => 'Fixed Rate',
        'fee' => 2000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 170,
    ],
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: 1,001 - 3,000 m²',
        'scale' => 'Fixed Rate',
        'fee' => 110000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 180,
    ],
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: 3,001 - 5,000 m²',
        'scale' => 'Fixed Rate',
        'fee' => 150000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 190,
    ],
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: 5,001 - 10,000 m²',
        'scale' => 'Fixed Rate',
        'fee' => 200000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 200,
    ],
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: 10,001 - 20,000 m²',
        'scale' => 'Fixed Rate',
        'fee' => 250000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 210,
    ],
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: 20,001 - 30,000 m²',
        'scale' => 'Fixed Rate',
        'fee' => 300000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 220,
    ],
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: 30,001 - 40,000 m²',
        'scale' => 'Fixed Rate',
        'fee' => 350000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 230,
    ],
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: 40,001 - 50,000 m²',
        'scale' => 'Fixed Rate',
        'fee' => 400000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 240,
    ],
    [
        'category' => '4. Final Certificate Fees (After completion of construction following Provisional/Semi Certificate)',
        'item_no' => null,
        'description_en' => 'Floor Area: More than 50,001 m²',
        'scale' => 'Fixed Rate',
        'fee' => 450000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 250,
    ],

    // 5. Field Inspection Fees (Constructed Outside the Boundary of Western Province)
    [
        'category' => '5. Field Inspection Fees (Constructed Outside the Boundary of Western Province)',
        'item_no' => null,
        'description_en' => '≤ 5 Condominium Units within a Parcel',
        'scale' => 'Transport Charge',
        'fee' => 12.00,
        'fee_display' => null,
        'remarks' => 'Rate per Kilometer. Government taxes applicable.',
        'order' => 260,
    ],
    [
        'category' => '5. Field Inspection Fees (Constructed Outside the Boundary of Western Province)',
        'item_no' => null,
        'description_en' => '> 5 Condominium Units within a Parcel',
        'scale' => 'Transport Charge',
        'fee' => 20.00,
        'fee_display' => null,
        'remarks' => 'Rate per Kilometer. Government taxes applicable.',
        'order' => 270,
    ],

    // 6. Inspection Fees (Constructed in Colombo, Gampaha, and Kalutara Districts)
    [
        'category' => '6. Inspection Fees (Constructed in Colombo, Gampaha, and Kalutara Districts)',
        'item_no' => null,
        'description_en' => 'Gampaha & Kalutara Districts (Outside Colombo)',
        'scale' => 'Transport Charge',
        'fee' => 20.00,
        'fee_display' => null,
        'remarks' => 'Rate per Kilometer. Together with government taxes.',
        'order' => 280,
    ],

    // 7. Renewal of a Semi or Provisional Condominium Plan (Annually)
    [
        'category' => '7. Renewal of a Semi or Provisional Condominium Plan (Annually)',
        'item_no' => null,
        'description_en' => 'Floor Area: Up to 1,000 m²',
        'scale' => 'Annual Rate',
        'fee' => 2000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 290,
    ],
    [
        'category' => '7. Renewal of a Semi or Provisional Condominium Plan (Annually)',
        'item_no' => null,
        'description_en' => 'Floor Area: 1,001 - 3,000 m²',
        'scale' => 'Annual Rate',
        'fee' => 7500.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 300,
    ],
    [
        'category' => '7. Renewal of a Semi or Provisional Condominium Plan (Annually)',
        'item_no' => null,
        'description_en' => 'Floor Area: 3,001 - 5,000 m²',
        'scale' => 'Annual Rate',
        'fee' => 15000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 310,
    ],
    [
        'category' => '7. Renewal of a Semi or Provisional Condominium Plan (Annually)',
        'item_no' => null,
        'description_en' => 'Floor Area: 5,001 - 10,000 m²',
        'scale' => 'Annual Rate',
        'fee' => 20000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 320,
    ],
    [
        'category' => '7. Renewal of a Semi or Provisional Condominium Plan (Annually)',
        'item_no' => null,
        'description_en' => 'Floor Area: More than 10,001 m²',
        'scale' => 'Annual Rate',
        'fee' => 25000.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 330,
    ],

    // 8. Amendments with Unchanged Total Area (Nominal Fee Levying Scheme)
    [
        'category' => '8. Amendments with Unchanged Total Area (Nominal Fee Levying Scheme)',
        'item_no' => null,
        'description_en' => 'Less than 5 units',
        'scale' => 'Nominal Rate',
        'fee' => 1000.00,
        'fee_display' => null,
        'remarks' => 'Area in square meters remains unchanged. Taxes added.',
        'order' => 340,
    ],
    [
        'category' => '8. Amendments with Unchanged Total Area (Nominal Fee Levying Scheme)',
        'item_no' => null,
        'description_en' => 'Units from 06 - 10',
        'scale' => 'Nominal Rate',
        'fee' => 2500.00,
        'fee_display' => null,
        'remarks' => 'Area in square meters remains unchanged. Taxes added.',
        'order' => 350,
    ],
    [
        'category' => '8. Amendments with Unchanged Total Area (Nominal Fee Levying Scheme)',
        'item_no' => null,
        'description_en' => 'Units from 11 - 20',
        'scale' => 'Nominal Rate',
        'fee' => 5000.00,
        'fee_display' => null,
        'remarks' => 'Area in square meters remains unchanged. Taxes added.',
        'order' => 360,
    ],
    [
        'category' => '8. Amendments with Unchanged Total Area (Nominal Fee Levying Scheme)',
        'item_no' => null,
        'description_en' => 'Units from 21 - 30',
        'scale' => 'Nominal Rate',
        'fee' => 15000.00,
        'fee_display' => null,
        'remarks' => 'Area in square meters remains unchanged. Taxes added.',
        'order' => 370,
    ],
    [
        'category' => '8. Amendments with Unchanged Total Area (Nominal Fee Levying Scheme)',
        'item_no' => null,
        'description_en' => 'Units from 31 - 40',
        'scale' => 'Nominal Rate',
        'fee' => 2500.00,
        'fee_display' => null,
        'remarks' => 'Area in square meters remains unchanged. Taxes added.',
        'order' => 380,
    ],
    [
        'category' => '8. Amendments with Unchanged Total Area (Nominal Fee Levying Scheme)',
        'item_no' => null,
        'description_en' => 'Units from 41 - 50',
        'scale' => 'Nominal Rate',
        'fee' => 30000.00,
        'fee_display' => null,
        'remarks' => 'Area in square meters remains unchanged. Taxes added.',
        'order' => 390,
    ],
    [
        'category' => '8. Amendments with Unchanged Total Area (Nominal Fee Levying Scheme)',
        'item_no' => null,
        'description_en' => 'More than 50 units',
        'scale' => 'Nominal Rate',
        'fee' => 50000.00,
        'fee_display' => null,
        'remarks' => 'Area in square meters remains unchanged. Taxes added.',
        'order' => 400,
    ],

    // 9 & 10. Secondary Processing & Documentation Fees
    [
        'category' => '9 & 10. Secondary Processing & Documentation Fees',
        'item_no' => '9',
        'description_en' => 'Processing fee for Provisional or Semi',
        'scale' => 'Advance Payment',
        'fee' => 0.00,
        'fee_display' => '50%',
        'remarks' => '50% of the fee paid at the time of obtaining the final certificate to be deducted.',
        'order' => 410,
    ],
    [
        'category' => '9 & 10. Secondary Processing & Documentation Fees',
        'item_no' => '10',
        'description_en' => 'Obtaining a Certified True Copy of Certificates',
        'scale' => 'Fixed Rate',
        'fee' => 1500.00,
        'fee_display' => null,
        'remarks' => 'Government taxes applicable.',
        'order' => 420,
    ],

    // Field Inspection Fees for De-registration/Dismantling
    [
        'category' => 'Field Inspection Fees for De-registration/Dismantling',
        'item_no' => null,
        'description_en' => 'Properties located Outside Western Province',
        'scale' => 'Transport Charge',
        'fee' => 30.00,
        'fee_display' => null,
        'remarks' => 'Rate per Kilometer. Not applicable if transport facilities are provided.',
        'order' => 430,
    ],
    [
        'category' => 'Field Inspection Fees for De-registration/Dismantling',
        'item_no' => null,
        'description_en' => 'Properties located in Western Province (Outside Colombo)',
        'scale' => 'Fixed Field Fee',
        'fee' => 7500.00,
        'fee_display' => null,
        'remarks' => 'Flat field inspection fee. Government taxes applicable.',
        'order' => 440,
    ]
];

foreach ($tariffs as $t) {
    ApplicationTariff::create($t);
}

echo "Database Seeded with PDF values successfully.\n";
